version: '3.8'
services:
  redis:
    image: redis:7
    container_name: tempshare-redis
    restart: unless-stopped
    ports:
      - "6380:6379"

  web:
    build: .
    container_name: tempshare-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
