# fly.toml app configuration file generated for tempshare-web on 2025-06-15T14:34:28+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tempshare-web'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
